apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmus-admission-server
  namespace: litmus
  labels:
    app: litmus-admission-server
    litmuschaos.io/component-name: litmus-admission-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litmus-admission-server
  template:
    metadata:
      labels:
        app: litmus-admission-server
    spec:
      serviceAccountName: litmus-admission-server
      containers:
        - name: server
          image: litmuschaos/admission-controller:ci
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          env:
            - name: ALLOWED_ORIGIN_SERVICE_ACCOUNTS
              value: '["litmus-admin","litmus"]'
            - name: ALLOWED_ORIGIN_IMAGES
              value: '["^.*/litmuschaos/go-runner:.*$","^.*/litmuschaos/chaos-operator:.*$"]'
            - name: ALLOWED_TARGET_IMAGES
              value: '["^.*/litmuschaos/go-runner:.*$"]'
            - name: TARGET_SERVICE_ACCOUNT
              value: "litmus-admin"
            - name: SELF_MANAGED_DEPENDENCIES
              value: "true"
            - name: CHAOS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: litmus-admission-server-service
  namespace: litmus
spec:
  selector:
    app: litmus-admission-server
  ports:
    - port: 443
      targetPort: 8443