apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-admission-server
  namespace: litmus
  labels:
    app.kubernetes.io/name: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: litmus-admission-server-role
  namespace: litmus
  labels:
    app.kubernetes.io/name: litmus
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get","list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus-admission-server-role-binding
  namespace: litmus
  labels:
    app.kubernetes.io/name: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus-admission-server-role
subjects:
  - kind: ServiceAccount
    name: litmus-admission-server
    namespace: litmus
